[features]
seeds = false
skip-lint = false
[programs.localnet]
shakeout = "GauoQBkGoNCjzZ9CnFwijL9FZutmjYBHZovVc2MenTnL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/raidr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
